# Generated by Django 4.0.5 on 2022-07-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, null=True, verbose_name='назва категорії')),
                ('category_img', models.ImageField(null=True, upload_to='document_gradient', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=200, null=True, verbose_name='назва документа')),
                ('document_url', models.CharField(max_length=400, null=True, verbose_name='посилання на google document')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.category')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
    ]
