# Generated by Django 4.0.5 on 2022-08-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roli_ho_ua',
            field=models.EmailField(max_length=70, null=True, unique=True, verbose_name='ролі.хо.юа'),
        ),
    ]
